syntax = "proto3";

option csharp_namespace = "MiaGRPC";
package MiaGRPC;



///////////////////////////////////USER/////////////////////////////////////////////

message UserData {
	string id = 1;
	string name = 2;
}

message SetUserRequest {
	string id = 1;
	string name = 2;
}

message GetUsersResponse {
	repeated UserData data = 1;
}

///////////////////////////////////SVM/////////////////////////////////////////////

message SvmData {
	string id = 1;
	string name = 2;
	repeated string users = 3;
	bool create_negative = 4;
	bool create_unknown = 5;
}

message SetSvmRequest {
	string id = 1;
	string name = 2;
	repeated string users = 3;
	bool create_negative = 4;
	bool create_unknown = 5;
}

message GetSvmsResponse {
	repeated SvmData data = 1;
}

///////////////////////////////////IMAGE/////////////////////////////////////////////

message ImageData {
	string id = 1;
    string name = 2;       
    bytes image_bytes = 3;  
}

message IndexRequest {
	string user_id = 1;
	string source = 2;
	string id = 3;
}

message DataRequest {
	string user_id = 1;
	string source = 2;
	repeated string ids = 3;
}

message RemoveDataRequest {
	string user_id = 1;
	string source = 2;
	repeated string ids = 3;
}

message SetDataRequest {
	string id = 1;
	string source = 2;
	string name = 3;
	string reference = 4;
	bytes image_bytes = 5; 
}

message IndexResponse {
	repeated ImageData data = 1;
}
message DataResponse {
    repeated ImageData images = 1;
}

message MiaResponse {
	string response = 1;
}


///////////////////////////////////RECOGNITION/////////////////////////////////////////////

message RecognitionRequest {
	bytes image = 1;
}

message RecognitionResponse {
	string user_id = 1;
	string name = 2;
	bytes image = 3;
}


service MiaService {

///////////////////////////////////USER/////////////////////////////////////////////

	rpc CreateUser(SetUserRequest) returns (GetUsersResponse);

	rpc ReadUsers(SetUserRequest) returns (GetUsersResponse);

	rpc UpdateUser(SetUserRequest) returns (GetUsersResponse);

	rpc DeleteUser(SetUserRequest) returns (GetUsersResponse);

///////////////////////////////////SVM/////////////////////////////////////////////

	rpc CreateSvm(SetSvmRequest) returns (GetSvmsResponse);

	rpc ReadSvms(SetSvmRequest) returns (GetSvmsResponse);

	rpc UpdateSvm(SetSvmRequest) returns (GetSvmsResponse);

	rpc DeleteSvm(SetSvmRequest) returns (GetSvmsResponse);

	rpc TrainSvm(SetSvmRequest) returns (MiaResponse);


/////////////////////////////////IMAGES///////////////////////////////////////////////


	rpc ReadIndex(IndexRequest) returns (IndexResponse);

	rpc ReadData(DataRequest) returns (stream ImageData);

	rpc SetData(stream SetDataRequest) returns (MiaResponse);
	
	rpc RemoveData(RemoveDataRequest) returns (MiaResponse);

/////////////////////////////////RECOGNITION///////////////////////////////////////////////

	rpc Recognize(stream RecognitionRequest) returns (stream RecognitionResponse);

}



